# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: windows-2022

steps:
- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: JavaToolInstaller@0
  displayName: Setup Java
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Bash@3
  displayName: Install MAUI
  inputs:
    targetType: 'inline'
    script: |
      dotnet nuget locals all --clear 
      dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
      dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

# dotnet nuget list source is to fix race condition in dotnet tool restore. Remove when https://github.com/NuGet/Home/issues/7503 is fixed.
- script:  |
    dotnet nuget list source
    dotnet tool restore
  displayName: 'Restore Tools'

- script: dotnet gitversion /output buildserver /nofetch
  displayName: 'GitVersion'
  
- script: dotnet cake --target=Sonar
  displayName: 'Sonar'
  env:
    SONAR_TOKEN: $(SONAR_TOKEN)

- script: dotnet cake --target=NuGetPack
  displayName: 'NuGet Pack'

- script: dotnet cake --target=NuGetPush
  displayName: 'NuGet Push'
  env:
    NUGET_API_KEY: $(NUGET_API_KEY)

- script: dotnet cake --target=Publish
  displayName: 'Publish'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'alexfdezsauco (4)'
    repositoryName: 'alexfdezsauco/Nothing.Nauta'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: '.*'
    title: 'Nauta Session $(GitVersion.NuGetVersion)'
    assets: '$(Build.SourcesDirectory)/output/zip/*.zip'
    isPreRelease: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'